### ISSUE TITLE
Sophie can login to Jitwin with Microsoft Active Directory

### ISSUE THREAD

**Issue by mtonosaki** [mtonosaki/Jitwin#4]
**GIVEN**
_Sophie_ sees Login button in Jitwin homepage.

**WHEN**
_Sophie_ click the login button.

**THEN**
**IF** interactive login is requested,
_Sophie_ can input login account and password
**AND** can accept/reject OAuth permission if it is necessary
**AND** _Sophie_ sees Top page
**AND** sees her display name of azure active directory.

**NOTE**
if non interactive mode, Sophie must not input her account/password and just she sees Top page automatically.

**Comment by mtonosaki** [comment]
### TODO
- [ ] Make AzureAD application.
- [ ] Make client secret of the aad application.
- [ ] Spring Security environment.
- [ ] Login support on the backend.
- [ ] Login support on the frontend.
- [ ] Call /me GraphAPI to show her display name.

**Comment by mtonosaki** [comment]
![Image](https://user-images.githubusercontent.com/34669114/190977349-9278c7e9-e41a-4e7c-b901-81c0c71e368e.png)


![Image](https://user-images.githubusercontent.com/34669114/190977425-ea909c8c-92eb-4dce-83fd-2b2005a6e557.png)



![Image](https://user-images.githubusercontent.com/34669114/190977191-c07373bf-6b12-4b85-816f-133cc3d03527.png)
